<?
	$galeriaPrincipal=array(
		"imagenes/cuadrosOleo/gerlo03_bodegon2.jpg",
		"imagenes/cuadrosOleo/gerlo_bodegon4.jpg",
		"imagenes/cuadrosOleo/gerlop_1.jpg",
		"imagenes/cuadrosOleo/gerlop_2.jpg",
		"imagenes/cuadrosOleo/gerlop_3.jpg",
		"imagenes/cuadrosOleo/gerlop_4.jpg",
		"imagenes/cuadrosOleo/gerlop_5.jpg",
		"imagenes/cuadrosOleo/gerlop_6.jpg",
		"imagenes/cuadrosOleo/gerlop_7.jpg",
		"imagenes/cuadrosOleo/gerlop93_bodegon.jpg",
		"imagenes/cuadrosOleo/gerlop_construccion1.jpg",
		"imagenes/cuadrosOleo/gerlop_construccion2.jpg"
	);

	$galeriaPinturas=array(
		"imagenes/pinturas/pintura1.jpg",
		"imagenes/pinturas/pintura2.jpg",
		"imagenes/pinturas/portada.jpg"
	);

	$galeriaDibujos=array(
		"imagenes/dibujos/dibujo0.jpg",
		"imagenes/dibujos/dibujo1.jpg",
		"imagenes/dibujos/dibujo2.jpg",
		"imagenes/dibujos/dibujo3.jpg",
		"imagenes/dibujos/dibujo4.jpg"
	);
	$galeriaGrabados=array(
		"imagenes/cuadrosOleo/gerlop_5.jpg",
		"imagenes/cuadrosOleo/gerlop_6.jpg"
	);
?>
